name: Salesforce Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Create sfdx-auth.txt from secret
        run: echo "${{ 'force://PlatformCLI::5Aep861GSSd.UBhhUKVe9ONt3cyab4JPDGXVD9PW3BWaC9t3VnQhAS0KBPXK2GTUb2VJqxt.a8TdNyLp6P55lXv@puttisreadingroom-dev-ed.develop.my.salesforce.com' }}"

      - name: Authorize Salesforce Org
        run: sfdx auth:sfdxurl:store -f --setalias DevHub --setdefaultdevhubusername
        
      - name: Deploy to Salesforce
        run: sfdx force:source:deploy -p force-app/main/default -u DevHub --wait 10
