name: Salesforce Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authorize Salesforce Org
        run: sfdx auth:sfdxurl:store -f sfdx-auth.txt --setalias DevHub --setdefaultdevhub vmsyadav@prr.com

      - name: Deploy to Salesforce
        run: sf project deploy start --metadata-dir force-app
