name: Moxie IntDev Deployment

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - pDeployment_Intdev
    paths:
      - 'force-app/**'
    types: [closed]
  
jobs:
  DeployToIntDev:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    environment: IntDev
    steps:
      - uses: actions/checkout@v3
      - name: Install Salesforce CLI
        shell: bash
        run: |
          npm install -g @salesforce/cli
          sf --version
      - name: Login to Environment
        shell: bash
        run: |
          sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
      - name: Deploy to Environment
        shell: bash
        run: |
          deployFlags=(
              --manifest manifest/package.xml
              --test-level RunSpecifiedTests 
              --tests ${{ vars.TEST_CLASSES }}
              --verbose
            )
          sf project deploy start "${deployFlags[@]}"
